/**
 * Snippet library — the seven authored language paths.
 *
 * Every entry carries a `title` (shown above the stage), a one-line `intro`
 * (what the program does and why it's worth typing) and a `topic` chip.
 * Three per difficulty, so "New snippet" always has somewhere to go.
 */

export const CORE_SNIPPETS = {
  javascript: [
    { difficulty: 'easy', title: 'Sum an array', topic: 'reduce', intro: 'Folds a list of numbers into one total — the smallest useful reduce.', code: `const total = (nums) =>\n  nums.reduce((sum, n) => sum + n, 0);\n\nconsole.log(total([4, 8, 15, 16]));` },
    { difficulty: 'easy', title: 'Capitalise words', topic: 'strings', intro: 'Splits on spaces, upper-cases each first letter, joins back.', code: `function titleCase(text) {\n  return text\n    .split(' ')\n    .map((w) => w[0].toUpperCase() + w.slice(1))\n    .join(' ');\n}` },
    { difficulty: 'easy', title: 'Debounce a callback', topic: 'closures', intro: 'Delays a function until the caller stops firing it — the classic search-box guard.', code: `function debounce(fn, wait) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), wait);\n  };\n}` },

    { difficulty: 'normal', title: 'Fetch with retry', topic: 'async', intro: 'Retries a failed request with exponential back-off before giving up.', code: `async function fetchJSON(url, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    const res = await fetch(url);\n    if (res.ok) return res.json();\n    await new Promise((r) => setTimeout(r, 2 ** i * 100));\n  }\n  throw new Error('request failed');\n}` },
    { difficulty: 'normal', title: 'Deep clone', topic: 'recursion', intro: 'Copies nested objects and arrays so mutations cannot leak back to the original.', code: `function clone(value) {\n  if (value === null || typeof value !== 'object') return value;\n  if (Array.isArray(value)) return value.map(clone);\n  return Object.fromEntries(\n    Object.entries(value).map(([k, v]) => [k, clone(v)]),\n  );\n}` },
    { difficulty: 'normal', title: 'Event emitter', topic: 'patterns', intro: 'A minimal pub/sub: subscribe to a name, emit to everyone listening.', code: `class Emitter {\n  #handlers = new Map();\n\n  on(name, fn) {\n    this.#handlers.set(name, [...(this.#handlers.get(name) ?? []), fn]);\n  }\n\n  emit(name, payload) {\n    (this.#handlers.get(name) ?? []).forEach((fn) => fn(payload));\n  }\n}` },

    { difficulty: 'hard', title: 'Group by key', topic: 'reduce', intro: 'Buckets a list into an object keyed by whatever the callback returns.', code: `const groupBy = (items, keyOf) =>\n  items.reduce((acc, item) => {\n    const key = keyOf(item);\n    (acc[key] ??= []).push(item);\n    return acc;\n  }, {});` },
    { difficulty: 'hard', title: 'Memoise with a cache key', topic: 'closures', intro: 'Caches results by serialised arguments so repeat calls are free.', code: `const memoize = (fn, cache = new Map()) => (...args) => {\n  const key = JSON.stringify(args);\n  if (!cache.has(key)) cache.set(key, fn(...args));\n  return cache.get(key);\n};` },
    { difficulty: 'hard', title: 'Promise pool', topic: 'concurrency', intro: 'Runs tasks with a hard concurrency ceiling instead of firing them all at once.', code: `async function pool(tasks, limit) {\n  const running = new Set();\n  const out = [];\n  for (const task of tasks) {\n    const p = task().finally(() => running.delete(p));\n    running.add(p);\n    out.push(p);\n    if (running.size >= limit) await Promise.race(running);\n  }\n  return Promise.all(out);\n}` },

    { difficulty: 'expert', title: 'Async iterator chunking', topic: 'generators', intro: 'Batches an async stream into fixed-size chunks without buffering everything.', code: `async function* chunked(iter, size) {\n  let buf = [];\n  for await (const item of iter) {\n    buf.push(item);\n    if (buf.length === size) {\n      yield buf;\n      buf = [];\n    }\n  }\n  if (buf.length) yield buf;\n}` },
    { difficulty: 'expert', title: 'Proxy-based observable', topic: 'metaprogramming', intro: 'Wraps an object so every write notifies a listener — reactivity in nine lines.', code: `const observable = (target, onChange) =>\n  new Proxy(target, {\n    set(obj, key, value) {\n      const prev = obj[key];\n      obj[key] = value;\n      if (prev !== value) onChange(key, value, prev);\n      return true;\n    },\n  });` },
    { difficulty: 'expert', title: 'Tagged template escaping', topic: 'templates', intro: 'A tag function that escapes every interpolated value before it reaches HTML.', code: `const escape = (s) =>\n  String(s).replace(/[&<>"]/g, (c) => \`&#\${c.charCodeAt(0)};\`);\n\nconst html = (strings, ...values) =>\n  strings.reduce((out, str, i) =>\n    out + str + (i < values.length ? escape(values[i]) : ''), '');` },
  ],

  typescript: [
    { difficulty: 'easy', title: 'Typed result union', topic: 'unions', intro: 'Models success and failure as one type the compiler forces you to unwrap.', code: `type Result<T> =\n  | { ok: true; value: T }\n  | { ok: false; error: string };\n\nconst ok = <T,>(value: T): Result<T> => ({ ok: true, value });` },
    { difficulty: 'easy', title: 'Readonly config', topic: 'const assertions', intro: 'A frozen literal whose exact string types survive inference.', code: `const CONFIG = {\n  host: 'localhost',\n  port: 8080,\n  secure: false,\n} as const;\n\ntype Config = typeof CONFIG;` },
    { difficulty: 'easy', title: 'Optional chaining helper', topic: 'narrowing', intro: 'A type guard that removes null and undefined from a union.', code: `function isPresent<T>(value: T | null | undefined): value is T {\n  return value !== null && value !== undefined;\n}\n\nconst names = raw.filter(isPresent);` },

    { difficulty: 'normal', title: 'Discriminated shapes', topic: 'guards', intro: 'A tagged union the compiler can exhaustively narrow on `kind`.', code: `interface Circle { kind: 'circle'; r: number }\ninterface Square { kind: 'square'; side: number }\ntype Shape = Circle | Square;\n\nfunction area(s: Shape): number {\n  return s.kind === 'circle' ? Math.PI * s.r ** 2 : s.side ** 2;\n}` },
    { difficulty: 'normal', title: 'Generic repository', topic: 'generics', intro: 'One interface, any entity — the shape most data layers converge on.', code: `interface Repo<T, K = string> {\n  get(id: K): Promise<T | null>;\n  save(entity: T): Promise<void>;\n  remove(id: K): Promise<boolean>;\n}` },
    { difficulty: 'normal', title: 'Exhaustive switch', topic: 'never', intro: 'Uses `never` so adding a case to the union becomes a compile error.', code: `function assertNever(x: never): never {\n  throw new Error(\`unexpected: \${JSON.stringify(x)}\`);\n}\n\nfunction label(s: Shape): string {\n  switch (s.kind) {\n    case 'circle': return 'round';\n    case 'square': return 'boxy';\n    default: return assertNever(s);\n  }\n}` },

    { difficulty: 'hard', title: 'Deep readonly', topic: 'mapped types', intro: 'Recursively freezes a type at every level of nesting.', code: `type DeepReadonly<T> = {\n  readonly [K in keyof T]: T[K] extends object\n    ? DeepReadonly<T[K]>\n    : T[K];\n};` },
    { difficulty: 'hard', title: 'Pick by value type', topic: 'conditional types', intro: 'Keeps only the keys whose values match a given type.', code: `type KeysOfType<T, V> = {\n  [K in keyof T]: T[K] extends V ? K : never;\n}[keyof T];\n\ntype StringKeys<T> = Pick<T, KeysOfType<T, string>>;` },
    { difficulty: 'hard', title: 'Builder with fluent types', topic: 'generics', intro: 'Each call widens the accumulated type, so the final build is fully typed.', code: `class Builder<T = {}> {\n  private data = {} as T;\n\n  with<K extends string, V>(key: K, value: V): Builder<T & Record<K, V>> {\n    (this.data as never)[key] = value;\n    return this as never;\n  }\n\n  build(): T {\n    return this.data;\n  }\n}` },

    { difficulty: 'expert', title: 'Template literal keys', topic: 'type-level', intro: 'Derives `onFoo` handler names from a union of event names.', code: `type EventName<T extends string> = \`on\${Capitalize<T>}\`;\n\ntype Handlers<T extends string> = {\n  [K in T as EventName<K>]: (payload: unknown) => void;\n};` },
    { difficulty: 'expert', title: 'Path-safe get', topic: 'type-level', intro: 'Types a dotted lookup so `get(obj, "a.b")` knows its own return type.', code: `type Path<T, P extends string> =\n  P extends \`\${infer K}.\${infer Rest}\`\n    ? K extends keyof T ? Path<T[K], Rest> : never\n    : P extends keyof T ? T[P] : never;` },
    { difficulty: 'expert', title: 'Branded primitives', topic: 'nominal typing', intro: 'Stops a UserId being passed where an OrderId is expected.', code: `declare const brand: unique symbol;\ntype Brand<T, B> = T & { readonly [brand]: B };\n\ntype UserId = Brand<string, 'UserId'>;\ntype OrderId = Brand<string, 'OrderId'>;` },
  ],

  python: [
    { difficulty: 'easy', title: 'Word frequency', topic: 'dicts', intro: 'Counts how often each word appears — the "hello world" of text processing.', code: `def word_count(text):\n    counts = {}\n    for word in text.lower().split():\n        counts[word] = counts.get(word, 0) + 1\n    return counts` },
    { difficulty: 'easy', title: 'FizzBuzz', topic: 'control flow', intro: 'The interview classic, written the way you would actually write it.', code: `def fizzbuzz(n):\n    for i in range(1, n + 1):\n        if i % 15 == 0:\n            print("FizzBuzz")\n        elif i % 3 == 0:\n            print("Fizz")\n        elif i % 5 == 0:\n            print("Buzz")\n        else:\n            print(i)` },
    { difficulty: 'easy', title: 'Read a file safely', topic: 'context managers', intro: 'Opens, reads and closes a file even if something throws midway.', code: `def read_lines(path):\n    with open(path, encoding="utf-8") as f:\n        return [line.rstrip("\\n") for line in f]` },

    { difficulty: 'normal', title: 'Binary search', topic: 'algorithms', intro: 'Halves the search space each step — the reason sorted data is worth keeping.', code: `def bisect(items, target):\n    lo, hi = 0, len(items) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if items[mid] == target:\n            return mid\n        if items[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1` },
    { difficulty: 'normal', title: 'Dataclass model', topic: 'dataclasses', intro: 'Generates init, repr and equality from a handful of typed fields.', code: `from dataclasses import dataclass, field\n\n@dataclass(frozen=True)\nclass Order:\n    id: str\n    total: float\n    tags: list[str] = field(default_factory=list)` },
    { difficulty: 'normal', title: 'Group with defaultdict', topic: 'collections', intro: 'Buckets records by a key without checking whether the bucket exists.', code: `from collections import defaultdict\n\ndef group_by(rows, key):\n    out = defaultdict(list)\n    for row in rows:\n        out[key(row)].append(row)\n    return dict(out)` },

    { difficulty: 'hard', title: 'Memoising decorator', topic: 'decorators', intro: 'Wraps a function so identical calls are answered from a cache.', code: `from functools import wraps\n\ndef memoize(fn):\n    cache = {}\n\n    @wraps(fn)\n    def inner(*args):\n        if args not in cache:\n            cache[args] = fn(*args)\n        return cache[args]\n\n    return inner` },
    { difficulty: 'hard', title: 'Generator pipeline', topic: 'generators', intro: 'Chains lazy transforms so a huge file never lands in memory at once.', code: `def read(path):\n    with open(path) as f:\n        yield from f\n\ndef clean(lines):\n    for line in lines:\n        stripped = line.strip()\n        if stripped:\n            yield stripped` },
    { difficulty: 'hard', title: 'Retry with backoff', topic: 'error handling', intro: 'Retries a flaky call, sleeping longer after each failure.', code: `import time\n\ndef retry(fn, attempts=3, base=0.2):\n    for i in range(attempts):\n        try:\n            return fn()\n        except OSError:\n            if i == attempts - 1:\n                raise\n            time.sleep(base * 2 ** i)` },

    { difficulty: 'expert', title: 'Context manager', topic: 'protocols', intro: 'Implements the with-statement protocol by hand to time a block.', code: `import time\n\nclass Timer:\n    def __enter__(self):\n        self.start = time.perf_counter()\n        return self\n\n    def __exit__(self, *exc):\n        self.elapsed = time.perf_counter() - self.start\n        return False` },
    { difficulty: 'expert', title: 'Async gather with limit', topic: 'asyncio', intro: 'Bounds concurrency with a semaphore instead of flooding the event loop.', code: `import asyncio\n\nasync def bounded(tasks, limit=5):\n    sem = asyncio.Semaphore(limit)\n\n    async def run(task):\n        async with sem:\n            return await task\n\n    return await asyncio.gather(*(run(t) for t in tasks))` },
    { difficulty: 'expert', title: 'Descriptor protocol', topic: 'data model', intro: 'A reusable validated attribute, the machinery properties are built on.', code: `class Positive:\n    def __set_name__(self, owner, name):\n        self.name = f"_{name}"\n\n    def __get__(self, obj, objtype=None):\n        return getattr(obj, self.name)\n\n    def __set__(self, obj, value):\n        if value <= 0:\n            raise ValueError("must be positive")\n        setattr(obj, self.name, value)` },
  ],

  java: [
    { difficulty: 'easy', title: 'Hello, world', topic: 'program structure', intro: 'The entry point every Java program starts from.', code: `public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, TypeForge");\n    }\n}` },
    { difficulty: 'easy', title: 'Reverse a string', topic: 'strings', intro: 'Uses StringBuilder because String itself is immutable.', code: `public static String reverse(String input) {\n    StringBuilder sb = new StringBuilder(input);\n    return sb.reverse().toString();\n}` },
    { difficulty: 'easy', title: 'Sum with enhanced for', topic: 'arrays', intro: 'Walks an array without ever touching an index.', code: `public static int sum(int[] values) {\n    int total = 0;\n    for (int value : values) {\n        total += value;\n    }\n    return total;\n}` },

    { difficulty: 'normal', title: 'Stream grouping', topic: 'streams', intro: 'Filters then buckets a collection in one declarative pass.', code: `Map<String, List<User>> byCity = users.stream()\n    .filter(User::isActive)\n    .collect(Collectors.groupingBy(User::getCity));` },
    { difficulty: 'normal', title: 'Try-with-resources', topic: 'resources', intro: 'Closes the reader automatically, even when the body throws.', code: `try (BufferedReader in = Files.newBufferedReader(path)) {\n    return in.lines().toList();\n} catch (IOException e) {\n    throw new UncheckedIOException(e);\n}` },
    { difficulty: 'normal', title: 'Optional handling', topic: 'optional', intro: 'Expresses "might not be there" without returning null.', code: `public Optional<User> findByEmail(String email) {\n    return users.stream()\n        .filter(u -> u.email().equalsIgnoreCase(email))\n        .findFirst();\n}` },

    { difficulty: 'hard', title: 'Generic bounded method', topic: 'generics', intro: 'Works for any comparable type, with the bound enforced at compile time.', code: `public static <T extends Comparable<T>> T max(List<T> items) {\n    T best = items.get(0);\n    for (T item : items) {\n        if (item.compareTo(best) > 0) {\n            best = item;\n        }\n    }\n    return best;\n}` },
    { difficulty: 'hard', title: 'Builder pattern', topic: 'design patterns', intro: 'Constructs an immutable object one named field at a time.', code: `public static final class Builder {\n    private String name;\n    private int port = 8080;\n\n    public Builder name(String name) {\n        this.name = name;\n        return this;\n    }\n\n    public Server build() {\n        return new Server(name, port);\n    }\n}` },
    { difficulty: 'hard', title: 'Concurrent counter', topic: 'concurrency', intro: 'Increments safely from many threads without a lock.', code: `private final AtomicLong hits = new AtomicLong();\n\npublic long record() {\n    return hits.incrementAndGet();\n}\n\npublic long total() {\n    return hits.get();\n}` },

    { difficulty: 'expert', title: 'Record with validation', topic: 'records', intro: 'A compact constructor that enforces the invariant on construction.', code: `public record Point(int x, int y) {\n    public Point {\n        if (x < 0 || y < 0) {\n            throw new IllegalArgumentException("negative");\n        }\n    }\n}` },
    { difficulty: 'expert', title: 'Sealed hierarchy', topic: 'sealed types', intro: 'Closes a type hierarchy so switch can be checked for exhaustiveness.', code: `public sealed interface Shape permits Circle, Square {}\n\npublic record Circle(double r) implements Shape {}\npublic record Square(double side) implements Shape {}` },
    { difficulty: 'expert', title: 'CompletableFuture chain', topic: 'async', intro: 'Composes two async calls without blocking a thread between them.', code: `CompletableFuture<Report> report = fetchUser(id)\n    .thenCompose(user -> fetchOrders(user.id()))\n    .thenApply(Report::summarise)\n    .exceptionally(err -> Report.empty());` },
  ],

  c: [
    { difficulty: 'easy', title: 'Hello, world', topic: 'program structure', intro: 'Includes the standard IO header and returns a clean exit code.', code: `#include <stdio.h>\n\nint main(void) {\n    printf("Hello, TypeForge\\n");\n    return 0;\n}` },
    { difficulty: 'easy', title: 'Swap two integers', topic: 'pointers', intro: 'The first program that makes pointers click.', code: `void swap(int *a, int *b) {\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}` },
    { difficulty: 'easy', title: 'Factorial', topic: 'recursion', intro: 'A base case and a recursive step — nothing else.', code: `unsigned long factorial(unsigned n) {\n    if (n <= 1) {\n        return 1;\n    }\n    return n * factorial(n - 1);\n}` },

    { difficulty: 'normal', title: 'String length', topic: 'arrays', intro: 'Walks to the null terminator and returns the pointer distance.', code: `size_t str_len(const char *s) {\n    const char *p = s;\n    while (*p != '\\0') {\n        p++;\n    }\n    return (size_t)(p - s);\n}` },
    { difficulty: 'normal', title: 'Read a file', topic: 'file handling', intro: 'Opens a file, checks the result, and always closes it.', code: `int count_lines(const char *path) {\n    FILE *f = fopen(path, "r");\n    if (f == NULL) {\n        return -1;\n    }\n    int lines = 0, c;\n    while ((c = fgetc(f)) != EOF) {\n        if (c == '\\n') lines++;\n    }\n    fclose(f);\n    return lines;\n}` },
    { difficulty: 'normal', title: 'Bubble sort', topic: 'arrays', intro: 'Slow but honest — a good excuse to practise nested loops and indices.', code: `void sort(int *a, size_t n) {\n    for (size_t i = 0; i + 1 < n; i++) {\n        for (size_t j = 0; j + 1 < n - i; j++) {\n            if (a[j] > a[j + 1]) {\n                int t = a[j];\n                a[j] = a[j + 1];\n                a[j + 1] = t;\n            }\n        }\n    }\n}` },

    { difficulty: 'hard', title: 'Linked list push', topic: 'structs', intro: 'Allocates a node and prepends it — the core of every list.', code: `typedef struct Node {\n    int value;\n    struct Node *next;\n} Node;\n\nNode *push(Node *head, int value) {\n    Node *n = malloc(sizeof(Node));\n    if (n == NULL) return head;\n    n->value = value;\n    n->next = head;\n    return n;\n}` },
    { difficulty: 'hard', title: 'Dynamic array grow', topic: 'dynamic memory', intro: 'Doubles capacity with realloc, keeping the old block on failure.', code: `int push_back(int **data, size_t *len, size_t *cap, int value) {\n    if (*len == *cap) {\n        size_t next = *cap ? *cap * 2 : 4;\n        int *grown = realloc(*data, next * sizeof(int));\n        if (grown == NULL) return -1;\n        *data = grown;\n        *cap = next;\n    }\n    (*data)[(*len)++] = value;\n    return 0;\n}` },
    { difficulty: 'hard', title: 'Free a list', topic: 'dynamic memory', intro: 'Saves the next pointer before freeing — the bug everyone writes once.', code: `void free_list(Node *head) {\n    while (head != NULL) {\n        Node *next = head->next;\n        free(head);\n        head = next;\n    }\n}` },

    { difficulty: 'expert', title: 'Qsort comparator', topic: 'function pointers', intro: 'A descending comparator that avoids overflow from naive subtraction.', code: `int cmp_desc(const void *a, const void *b) {\n    int x = *(const int *)a;\n    int y = *(const int *)b;\n    return (y > x) - (y < x);\n}\n\nqsort(values, n, sizeof(int), cmp_desc);` },
    { difficulty: 'expert', title: 'Bit flags', topic: 'bitwise', intro: 'Sets, clears and tests individual bits in a flags word.', code: `#define FLAG_READ  (1u << 0)\n#define FLAG_WRITE (1u << 1)\n\nstatic inline unsigned set(unsigned f, unsigned bit)   { return f | bit; }\nstatic inline unsigned clear(unsigned f, unsigned bit) { return f & ~bit; }\nstatic inline int has(unsigned f, unsigned bit)        { return (f & bit) != 0; }` },
    { difficulty: 'expert', title: 'Generic swap with memcpy', topic: 'void pointers', intro: 'Swaps any two objects of equal size using a stack buffer.', code: `void swap_any(void *a, void *b, size_t size) {\n    unsigned char tmp[64];\n    if (size > sizeof(tmp)) return;\n    memcpy(tmp, a, size);\n    memcpy(a, b, size);\n    memcpy(b, tmp, size);\n}` },
  ],

  cpp: [
    { difficulty: 'easy', title: 'Hello, world', topic: 'program structure', intro: 'Stream output instead of format strings.', code: `#include <iostream>\n\nint main() {\n    std::cout << "Hello, TypeForge\\n";\n    return 0;\n}` },
    { difficulty: 'easy', title: 'Print a vector', topic: 'iterators', intro: 'A range-based for loop over a standard container.', code: `void print(const std::vector<int>& v) {\n    for (const auto& item : v) {\n        std::cout << item << ' ';\n    }\n    std::cout << '\\n';\n}` },
    { difficulty: 'easy', title: 'Class with constructor', topic: 'classes', intro: 'Member initialiser list, const method, private state.', code: `class Counter {\npublic:\n    explicit Counter(int start) : value_(start) {}\n\n    void bump() { ++value_; }\n    int value() const { return value_; }\n\nprivate:\n    int value_;\n};` },

    { difficulty: 'normal', title: 'Unique pointer factory', topic: 'RAII', intro: 'Ownership is expressed in the return type — no manual delete anywhere.', code: `std::unique_ptr<Session> open(const std::string& host) {\n    auto s = std::make_unique<Session>(host);\n    s->connect();\n    return s;\n}` },
    { difficulty: 'normal', title: 'Map lookup', topic: 'containers', intro: 'Finds a key without accidentally inserting it.', code: `int lookup(const std::unordered_map<std::string, int>& m,\n           const std::string& key) {\n    auto it = m.find(key);\n    return it == m.end() ? 0 : it->second;\n}` },
    { difficulty: 'normal', title: 'Lambda with capture', topic: 'lambdas', intro: 'Captures a threshold by value and uses it inside an algorithm.', code: `auto above = [threshold](const auto& v) {\n    return v > threshold;\n};\n\nauto n = std::count_if(data.begin(), data.end(), above);` },

    { difficulty: 'hard', title: 'Templated accumulate', topic: 'templates', intro: 'Works on any iterator pair and any accumulator type.', code: `template <typename It, typename T>\nT sum(It begin, It end, T init) {\n    for (; begin != end; ++begin) {\n        init += *begin;\n    }\n    return init;\n}` },
    { difficulty: 'hard', title: 'Operator overloading', topic: 'operators', intro: 'Adds two vectors with the syntax you would expect.', code: `struct Vec2 {\n    double x, y;\n\n    Vec2 operator+(const Vec2& o) const {\n        return {x + o.x, y + o.y};\n    }\n\n    bool operator==(const Vec2& o) const = default;\n};` },
    { difficulty: 'hard', title: 'RAII lock guard', topic: 'concurrency', intro: 'Locks on construction, unlocks on scope exit, exception-safe by design.', code: `int Counter::next() {\n    std::lock_guard<std::mutex> guard(mutex_);\n    return ++value_;\n}` },

    { difficulty: 'expert', title: 'Move constructor', topic: 'move semantics', intro: 'Steals the buffer and leaves the source safely empty.', code: `Buffer::Buffer(Buffer&& other) noexcept\n    : data_(other.data_), size_(other.size_) {\n    other.data_ = nullptr;\n    other.size_ = 0;\n}` },
    { difficulty: 'expert', title: 'Variadic template', topic: 'templates', intro: 'A fold expression that prints any number of arguments.', code: `template <typename... Args>\nvoid log(const Args&... args) {\n    ((std::cout << args << ' '), ...);\n    std::cout << '\\n';\n}` },
    { difficulty: 'expert', title: 'Constrained template', topic: 'concepts', intro: 'A concept that rejects non-numeric types at the call site.', code: `template <typename T>\nconcept Numeric = std::integral<T> || std::floating_point<T>;\n\ntemplate <Numeric T>\nT clamp(T v, T lo, T hi) {\n    return v < lo ? lo : (v > hi ? hi : v);\n}` },
  ],

  sql: [
    { difficulty: 'easy', title: 'Filtered select', topic: 'select', intro: 'Project a few columns, filter, order, and cap the result set.', code: `SELECT name, email\nFROM users\nWHERE active = TRUE\nORDER BY created_at DESC\nLIMIT 20;` },
    { difficulty: 'easy', title: 'Insert returning', topic: 'insert', intro: 'Writes a row and hands back the generated id in one round trip.', code: `INSERT INTO users (name, email)\nVALUES ('Ada', 'ada@example.com')\nRETURNING id, created_at;` },
    { difficulty: 'easy', title: 'Aggregate count', topic: 'aggregates', intro: 'Counts rows per group and orders by the busiest group.', code: `SELECT status, COUNT(*) AS total\nFROM orders\nGROUP BY status\nORDER BY total DESC;` },

    { difficulty: 'normal', title: 'Join with aggregate', topic: 'joins', intro: 'Keeps users with no orders visible, then filters on the count.', code: `SELECT u.name, COUNT(o.id) AS orders\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\nGROUP BY u.name\nHAVING COUNT(o.id) > 3;` },
    { difficulty: 'normal', title: 'Upsert', topic: 'conflicts', intro: 'Inserts, or updates the existing row when the key collides.', code: `INSERT INTO settings (user_id, theme)\nVALUES ($1, $2)\nON CONFLICT (user_id)\nDO UPDATE SET theme = EXCLUDED.theme, updated_at = now();` },
    { difficulty: 'normal', title: 'Index for a lookup', topic: 'indexing', intro: 'A partial index that only covers the rows queries actually touch.', code: `CREATE INDEX CONCURRENTLY idx_orders_pending\nON orders (user_id, created_at DESC)\nWHERE status = 'pending';` },

    { difficulty: 'hard', title: 'Window function', topic: 'windows', intro: 'Ranks rows inside each partition without collapsing them.', code: `SELECT\n  name,\n  score,\n  RANK() OVER (PARTITION BY team ORDER BY score DESC) AS rank\nFROM players;` },
    { difficulty: 'hard', title: 'Running total', topic: 'windows', intro: 'Sums every row up to the current one, ordered by date.', code: `SELECT\n  day,\n  amount,\n  SUM(amount) OVER (ORDER BY day\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running\nFROM revenue;` },
    { difficulty: 'hard', title: 'Lateral join', topic: 'joins', intro: 'Pulls the latest row per user without a correlated subquery per column.', code: `SELECT u.name, last.created_at\nFROM users u\nCROSS JOIN LATERAL (\n  SELECT created_at FROM orders o\n  WHERE o.user_id = u.id\n  ORDER BY created_at DESC LIMIT 1\n) AS last;` },

    { difficulty: 'expert', title: 'Recursive CTE', topic: 'CTEs', intro: 'Walks a parent/child tree to any depth in a single statement.', code: `WITH RECURSIVE tree AS (\n  SELECT id, parent_id, 1 AS depth FROM nodes WHERE parent_id IS NULL\n  UNION ALL\n  SELECT n.id, n.parent_id, t.depth + 1\n  FROM nodes n JOIN tree t ON n.parent_id = t.id\n)\nSELECT * FROM tree ORDER BY depth;` },
    { difficulty: 'expert', title: 'Transaction with lock', topic: 'transactions', intro: 'Moves money atomically, locking the row it is about to debit.', code: `BEGIN;\n  SELECT balance FROM accounts WHERE id = 1 FOR UPDATE;\n  UPDATE accounts SET balance = balance - 100 WHERE id = 1;\n  UPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;` },
    { difficulty: 'expert', title: 'Row level security', topic: 'security', intro: 'Restricts every query on the table to the current user\'s own rows.', code: `ALTER TABLE notes ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY notes_owner ON notes\n  USING (user_id = auth.uid())\n  WITH CHECK (user_id = auth.uid());` },
  ],
};
