-- Corrects the daily request caps seeded by 0019.
--
-- 0019 was generated by a script that read each provider out of providers.ts
-- using a fixed 1800-character window from the provider's opening brace. Three
-- of the four blocks are shorter than that, so their windows ran on into the
-- next provider and picked up the first `dailyLimit` they could see —
-- OpenRouter's 50/day free-tier cap — and wrote it onto all four.
--
-- The result was not a cosmetic slip. `day_limit` is what the console's daily
-- budget panel draws its progress bar against, so three providers appeared to
-- be four-fifths through a ceiling that does not exist, and an operator
-- reading that would throttle traffic for no reason.
--
-- Only OpenRouter publishes a cap. NULL means uncapped, and the console
-- already renders that as "uncapped" rather than as zero.
--
-- The generator now slices each block at the next provider's start instead of
-- at a character count. `max_temperature` was unaffected — it happened to be
-- set on the two providers whose windows did not overreach.

update public.ai_providers set day_limit = null  where id in ('nim', 'hcnsec', 'kira');
update public.ai_providers set day_limit = 50    where id = 'openrouter';

comment on column public.ai_providers.day_limit is
  'Requests per day the provider allows. NULL means uncapped — the console '
  'renders that as "uncapped", never as a limit of zero.';
